### ISSUE TITLE
The Blinds Node

### ISSUE THREAD

**Issue by danlun** [rdmtc/node-red-contrib-sun-position#164]
**Please consider the other places for Support:**

* [RedMatic Slack (chat like WhatsApp or Facebook Messenger)](https://join.slack.com/t/homematicuser/shared_invite/enQtNDgyNDM2OTkyMDA2LWY1YjY0NTE0NmY0OWM3YWUzMzAzMTgxYmRjMTMyOWE3NjkxNDdlMDY5ZjlhYzM5Nzg2N2U2YjdmNzNlYWNhNTU)
* [RedMatic Forum](https://homematic-forum.de/forum/viewforum.php?f=77)
* [RedMatic Wiki](https://github.com/rdmtc/RedMatic/wiki)

**Describe the Problem**
I want to get my blinds to open to 100% when either Azimuth >215 degrees or Altitude > 68 degrees. The close today when lux > 38 000 and that is working well (by another rule in HA, but I can't understand how I do the Blind node to open on the rules described. Must I have a trigger, its not that as soon as any of these two is fulfilled the blinds will open? Is a time trigger needed? And the output, how is that controlling my blinds? Sorry for these basic questions but I have really tried to read all documentation.

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**

* Version [e.g. 0.4.7]
* Node-Red Version
Installed via Home Assistant

**Additional context**

**Comment by Hypnos3** [comment]
Sorry for the late reply. Due to the general situation, I am currently unable to process the issues.
You can specify the altitude as a condition in the rules.

When the auto trigger is active, these types of rules are only re-evaluated at the set time interval. An external trigger is only necessary when a rule exists which based on environment variables, flow or global contexts and the node should be informed about a change of these data.
