### ISSUE TITLE
clock-timer differs from blind-control

### ISSUE THREAD

**Issue by Jo-Be-Co** [rdmtc/node-red-contrib-sun-position#186]
Hi,
the clock-timer as clone of the blind-control does not catch up with the latest updates on blind-control.

Maybe the similar parts should be more equal or even based on a central implementation.

Actually I have spotted some faulty behaviour where I would like to contribute some fixes:
- the 'trigger' option does not work correct
- setting autoTriggerTime in the node does not change the autoTrigger
- using boolean as payload for overwrite does not work if the value is 'false'

cheers,
   Jogi

**Comment by Hypnos3** [comment]
601/5000
I've already thought about merging the implementation. But in particular there are many small differences. This could also lead to downward compatibility problems (changing the properties in the outgoing message, etc.), so that such a massive change is only possible in a mayor version jump.

It's on my todo, but it's not a high priority.

To your findings:
- I dont understand what you mean with "the 'trigger' option does not work correct"?
- setting autoTriggerTime in the node seems to not work for the bind control and also not clock-timer, will be fixed for both in the next version
- the problem that boolean  for overwrite does not work will be fixed in the next version

**Comment by Jo-Be-Co** [comment]
> Hi,
> 
> I've already thought about merging the implementation. But in particular there are many small differences. This could also lead to downward compatibility problems (changing the properties in the outgoing message, etc.), so that such a massive change is only possible in a mayor version jump.
> 
> It's on my todo, but it's not a high priority.
> 
> To your findings:
> 
> * I don't understand what you mean with "the 'trigger' option does not work correct"? Can you please explain a little bit more the problem here?

In the code of the blind-control there is a check for "trigger/noOverwrite/triggerOnly". If this is found there won't be any changes on `expiring`, `importance`, `overwriteReason` or the level:
```javascript
        if (!onlyTrigger && node.nodeData.overwrite.active && isNaN(newPos)) {
            ...
        } else if (!onlyTrigger && !isNaN(newPos)) {
            ...
        }
```

`clock-timer` on the other hand will skip the search for `overrideData` in case of `onlyTrigger`. Otherwise `overrideData` will still be `undefined` so that the following is executed:
```javascript
        if (node.nodeData.overwrite.active) {
            node.debug(`overwrite active, check of nImportance=${nImportance} or nExpire=${nExpire}`);
            if (Number.isFinite(nExpire)) {
                node.debug(`set to new expiring time nExpire="${nExpire}"`);
                // set to new expiring time
                setExpiringOverwrite(node, dNow, nExpire, 'set new expiring time by message');
            }
            if (nImportance > 0) {
                // set to new importance
                node.nodeData.overwrite.importance = nImportance;
            }
            // node.debug(`overwrite exit true node.nodeData.overwrite.active=${node.nodeData.overwrite.active}, expire=${nExpire}`);
            return setOverwriteReason(node);
        }
```

Grüße ;-)

**Comment by Hypnos3** [comment]
can be tested in https://github.com/rdmtc/node-red-contrib-sun-position/releases/tag/1.2.0
