### ISSUE TITLE
Add Blind ID field

### ISSUE THREAD

**Issue by jonferreira** [rdmtc/node-red-contrib-sun-position#238]
Hi all.

Currently using the great node-red-contrib-clindcontroller-v2 but I've started working migration my system to node-red 1.X and Home Assistant and while researching found this node which seems awesome!
Struggling to understand some bits but I'll get there eventually.

**Is your feature request related to a problem? Please describe.**
Currently one needs a blind-node for each blind (I'm perfectly fine with that, that's exactly how I'm currently working with node-red-contrib-clindcontroller-v2) but there's no way to set a "blind id". That means that we need to connect each individual blind (blind-control) to another individual node that then handles the "output", e.g. HA call service node.

**Describe the solution you'd like**
By having a "blind id" field on blind-control node that means we can set up each individual blind as a blind-control node but then they can all output to the *same* function node (for example) since we receive the "blind id" and can then act accordingly.
For example, if you're using Home Assistant this "blind id" would be the HA "entity_id" that would be passed to a api-call-service node along with the blind level.

This would be incredible helpful and would cut in half the total required number of nodes to calculate and control blind position.

**Comment by Hypnos3** [comment]
Normally in node-red therefor is used the topic field for such a use-case. For example ther could be stored something like `shutter\blindID1\ whatelse`, for example. In the node, the topic can be influenced on various places.

On the one hand, the settings screen is already very cluttered, which is why I shy away from packing further information into it. On the other hand, there is still a request for roller shutters, which in addition to the curtain height can also influence the angle of the slats, to be able to provide additional information about the angle.

As a short-term solution, I may be able to include the name of the node in the messages that will be send.

**Comment by Hypnos3** [comment]
Is integrated in the 2.0.0-beta and can be installed and tested. See Releases Information on how to install the beta version.
