### ISSUE TITLE
Show the recalculate option also for the time offset with global or flow source

### ISSUE THREAD

**Issue by McPan** [rdmtc/node-red-contrib-sun-position#303]
I use the "time-inject" node (v1.2.4) to switch off different actuators depending on the position of the sun. So far, so good.

To adapt the whole thing a little bit to the brightness caused by the weather, I modify the switching point via a time offset, which is generated by the measurement of a brightness sensor.

Since the brightness sensor does not provide continuous measured values, I store the last measured value in a global variable, which is then used as the time offset.

In this case (offset with global source) the node does not offer the recalculation option.

**Request:** It would be nice if the recalculate option, just like for the actual time value with global- or flow-source, would also be displayed for the offset with global or flow source.

The icing on the cake would be if the recalculation time could be specified not only in fractions of hours, but also directly in minutes.

**Comment by Hypnos3** [comment]
There is no trigger mechanism or event in node-red if the flow or global variables change. Something like that was always rejected by the developers of node-Red, because it would not correspond to the concept.

I do not see this wish here according to the concept of and therefore the recalculation fits is the worst possible approach.

The time-Inject node is not the right approach here. I solve such problems myself, for example with the clock-timer node. With this one can retrigger the calculation with a message from the outside. A trigger can then in turn be a sensor.
