### ISSUE TITLE
[FR]Provide optional offset in the config for blind positions with actual window clearness to enable correct "sun on floor length"

### ISSUE THREAD

**Issue by mglaabde** [rdmtc/node-red-contrib-sun-position#371]
**Is your feature request related to a problem? Please describe.**
When using "length on the floor" config option, respectively setSunDataFloorLength, calculation is based on window top and window bottom position. However, with normal blinds, typically neither window position close to 0% nor 100% directly impact the length of the sun on the floor, because:
* Close to 100%, at first small slots are visible, before the blind actually starts to rise from the ground
* When starting to rise from the ground, there are typically some more cm that are covered by the window frame (i.e., still no impact on the sun length on the floor)

-> As a consequence, e.g., 20% of the overall scale doesn't have an impact on the sun on the floor at all.
Therefore, calculation is wrong, and sun on the floor length does not remain constant throughout the day
* Same is true for close to max blind openings, where the window frames again causes that no greater sun length on the floor can be reached

**Describe the solution you'd like**
Provide 1 or better 2 optional config values for the positions, where the blind actually starts to influence the sun on the floor length
1st config value for "sun on floor length min" position, e.g., as num value >= closed position (min)
2nd config value for "sun on floor length max" position, e.g., as num value <= open position (max)
Example:
closed position (min) = 0
open position (max) = 1
sun on floor length min = 0.25
sun on floor length max = 0.9
-> Accordingly, sun on floor length calculation would be based on the 2 optional values, given they are configured

**Describe alternatives you've considered**
You could do it externally to the blind node, e.g., by utilizing "range node", or even do the % blind position calculation to reach the sun on floor length completely externally to the node. However, IMHO, since the functionality for blind control based on sun on floor length is officially supported by the blind node, it should also provide means to do it correctly.

**Additional context**

**Comment by Hypnos3** [comment]
When I think about it, you can achieve this very easily by differentiating `closed position (min)` and `open position (max)`.

The calculation is much simpler than you might think. The lengthOnTheFloor value is only used to calculate where the sun falls in the window, using the top and bottom position as a limit and as a maximum and minimum for the shutter position:
![image](https://user-images.githubusercontent.com/12692680/149662679-d0c7b6a7-d71a-4281-b7f7-f27865c3f028.png)

So instead having `floor length min` and a `floor length max` you could change the window bottom and top position and  define a different blind open and closed position for the sun position calculation

When there covered by the window frame, then as the window bottom position in the node-settings a value should be taken as the position from when the sun calculation should be done. So the value of window bottom should be "real window bottom" + "window frame". The same for the window top which should be "real window top" - "window frame".

If I implement the desired "sun on floor length min" and "sun on floor length max", I would internally calculate only an offset for the lower fender position and the upper window position. and use this offsets for the check if the sun is below the window bottom or above the window top:
![image](https://user-images.githubusercontent.com/12692680/149663054-72d424dd-bcdf-4b98-a464-2e2374ad13a1.png)

Perhaps instead of  "sun on floor length min" and "sun on floor length max"  it would be better to be able to define this offset for "window below" and "window above"?

**Comment by mglaabde** [comment]
Thank you for your comprehensive answer.
I think the issue is with the following calculation:
`node.level.current = nodepos PrcToAbs_(node, (height - wBottom) / wTop - wBottom));`
and the function PrcToAbs https://github.com/rdmtc/node-red-contrib-sun-position/blob/a50a6f588f425e94f1cf6b80741c41eef997f75c/nodes/blind-control.js#L34-L35

**Comment by mglaabde** [comment]
Thank you for your comprehensive answer.
I think the issue is with the following calculation:
`node.level.current = nodepos PrcToAbs_(node, (height - wBottom) / wTop - wBottom));`
and the function PrcToAbs 
https://github.com/rdmtc/node-red-contrib-sun-position/blob/a50a6f588f425e94f1cf6b80741c41eef997f75c/nodes/blind-control.js#L34-L35
The percentage is calculated on and applied to the total range of the blind, i.e., levelTop, levelBottom.
Example:
```
wTop = 180; // as you proposed the real free space below the frame
wBottom = 20; // as you proposed the real free space below the frame
altitude=22; //22 degree = 0.38 rad
floorLength=200;
levelTop = 1;
levelBottom = 0;
```
This means:
height = tan(0.38)*200 = 80.81

(height - wBottom) / wTop - wBottom) = (80.81 - 20) / (180 - 20) = 38.01%

(node.nodeData.levelTop - node.nodeData.levelBottom) * levelPercent) + node.nodeData.levelBottom =
((1 - 0) * 38.01%) + 0 = 0.3801

This does not lead to a correct positioning of the blind, because
a) the calculation is not based on the actual window free space
b) due to the following nature of a classical blind

| Level  |  Description |
| --- | --- |
|  100%  |  Fully open: blind completely in the roller shutter box |
|  90%  |  blind came out of the roller shutter box and is at the level of the window frame, i.e., starts to influences the sun that falls into the window |
|  30%  |  blind already touches the window frame at the bottom, i.e., any further blind lowering does not influence how much sun falls into the window (besides a complete close that closes the slits between the slats |
|  0%  |  Fully closed: blind completely down and slits are closed too |

-> 38% is close to not letting any sun anymore in and definitely leads not to a sun on floor of 200.

**Comment by Hypnos3** [comment]
This depends heavily on the used blind. What is required here is not two values for the length on the ground, better will be an offset for open/closed blinds.
