### ISSUE TITLE
Version 2.0.6 seems to no longer emit at startup

### ISSUE THREAD

**Issue by ahartman** [rdmtc/node-red-contrib-sun-position#374]
Sorry, wrong node.

**Comment by Hypnos3** [comment]
There was a change in the blind control and the clock-timer node #369, but this should not result in no message being sent/emit  at all at start-up. Rather, the fact that messages are sent during startup is now reduced and the first message is sent/emit  after the startup has ended. The nodes should always work this way. Unfortunately there was a bug here, so that up to now messages were also sent during startup.

The startup time can be set in the advanced settings:
![image](https://user-images.githubusercontent.com/12692680/145367564-e0783d2b-94ff-45c5-9d4a-009619a18911.png)

The standard value (if nothing is defined here) is a random value between `300ms` and `700ms`. To switch this off completely, you have to enter the value `0` here.

Please reopen the Issue if there is still a problem.
