### ISSUE TITLE
Blind Control Example #3 rules not triggered

### ISSUE THREAD

**Issue by overdrive69** [rdmtc/node-red-contrib-sun-position#388]
**Describe the bug**
I testes the blind controller node with the example #3.
There is this option for 1sec is 30min input.
If i start this with the start/stop flow, the rules are not triggering.

**Screenshots**

![image](https://user-images.githubusercontent.com/8517462/148145700-8810883f-66ab-4d49-a412-c29b76ac91b7.png)

**Expected behavior**
Rules should trigger, and also override "Sonnesteuerung"

**System information (please complete the following information):**
 - Node Version 
 - Node-Red Version V2.1.4

**Additional context**

**Comment by Hypnos3** [comment]
The error is n the function node:
![image](https://user-images.githubusercontent.com/12692680/149656179-d18cb7bc-635a-4629-b969-2ec21f07c766.png)

in line 20 must be instead of `(isNAN` --> `(!isNAN`:
![image](https://user-images.githubusercontent.com/12692680/149656218-49be6897-898d-42a6-a299-6beff0982bc2.png)

Will be fixed in the next release!

**Comment by Hypnos3** [comment]
The issue should be fixed in the latest release.
