### ISSUE TITLE
Civil Dawn in Inject Enhanced and Within Time nodes are showing slightly different times.

### ISSUE THREAD

**Issue by adsavia** [rdmtc/node-red-contrib-sun-position#416]
**Describe the bug**
Inject Enhanced and Within Time Nodes do not agree on Civil Dawn (have not tried others).

**Screenshots**
![nr682](https://user-images.githubusercontent.com/22320894/155826819-caaa5b86-c8f3-4dbd-a278-4d1b3a8992a0.png)

**Expected behavior**
Civil Dawn Times should match?

**System information (please complete the following information):**
 - Node Version 2.1.1
 - Node-Red Version 2.2.0

**Additional context**

**Comment by Hypnos3** [comment]
Hello,

This is an expected behavior.

The time-inject node always shows the next timestamp - the timestamp of the next inject, whereas the within-time node always shows the timestamps for the current day.

The reason for this is that the within-time node determines the start and end time for the current day and then checks whether the current time is within this period. These determined times are simply output as status. The inject node always determines the next time and outputs this as status.

The function to determine the time is also not in the nodes themselves, but in the configuration node. As long as both nodes use the same configuration-node, it is 100% sure that they use the same time. Since both nodes use the same function for the determination of the time and this function the determined times even internally cached by day - that means, the times are not recalculated each time, but all nodes with the same configuration node use the same time. To thus differences in times can arise only by times for different days or configuration nodes.

Is this here a feature request, because to change in such a way that the within-time node after expiration of the time period outputs the next time period?

regards
(duplicate to #417)

**Comment by adsavia** [comment]
Also I think it's fine - no new feature necessary. The within-time node will update for the next day and work as expected? In other words it's okay to do a dusk to dawn range even though the end time is earlier.. I've always been a little confused about that but it works so...

**Comment by Hypnos3** [comment]
The within-time node check when a message arrives if it is still valid for the current day and if not it recalculates the times.

The within-time node also accepts if the end time is before the start time (dawn to sunrise) and will evaluate this correctly. May in this case the state is misleading.

**Comment by Hypnos3** [comment]
the latest version (currently beta) has a changed state text and shows extra icon if time goes over midnight:
![image](https://user-images.githubusercontent.com/12692680/158081772-29a8e7b3-5ff6-451f-b400-34f9d4bb25e2.png)
