### ISSUE TITLE
Status in Local Time [feature request]

### ISSUE THREAD

**Issue by marc-gist** [rdmtc/node-red-contrib-sun-position#8]
First... Thanks for the great node!
I would love to see the Node Status display times/etc in Local Time, rather than UTC, or have an option to toggle in the config of the node to do so?

**Comment by Hypnos3** [comment]
Thank you for this contribution.

There is currently no specific time zone setup. Currently the time will be used of the environment where node-red is installed. If there is used UTC, the shown time is in UTC. If the environment of Node-Red is in local time, the shown time is also in local time.

I have in plan to be able to select a different timezone for the output time as the environment of the node-red installation uses.

**Comment by marc-gist** [comment]
That is not true... Node-Red is UTC, and display in UTC no matter what I do, many other places state that is an issue, and use moment.js to display/get local time displayed properly.

**Comment by Hypnos3** [comment]
True is: Javascript deals internally with UTC and also the node-js does this. But the display of date and times is depending of the way you output it.

Here is the example of the Node Status display output
time-inject node:
![image](https://user-images.githubusercontent.com/12692680/54127039-32409b00-4409-11e9-825c-f1f7eb471d08.png)
within-time node:
![image](https://user-images.githubusercontent.com/12692680/54129009-9d8c6c00-440d-11e9-8774-e2ab3a60928e.png)

As you can see already "[toLocaleString()](https://www.w3schools.com/jsref/jsref_tolocalestring.asp)" method of the date object is used as output. But as I mean before this "local" depends on your node-js enviroment. (There are also problems with this in older versions of nodejs).

In my environments with nodejs 8 and 10 this is working fine and there the Node Status display is already in local time and not in UTC:
![image](https://user-images.githubusercontent.com/12692680/54126968-03c2c000-4409-11e9-8c7d-e312e6312ac3.png)
![image](https://user-images.githubusercontent.com/12692680/54126983-0fae8200-4409-11e9-84cb-d206dc8b21a4.png)

But I can understand that (depending on where you have installed node-red), you want to use a different time zone than the enviroment of node-js is using. (Maybe because you have no influence on it.) To thus I have in plan to be able to setup the desired timezone offset in the configuration node and uses this configuration for display instead of the "toLocaleString()" method of the date object.

This will help you, that in your case you can setup a different timezone than UTC there and see the status output in that time.

I already have prepared this in the Background, but I can not promise it will be included in the next major release.

**Comment by marc-gist** [comment]
Strange, as mine doesn't display in localtime, regardless of my settings.  I am running node-red v8 docker. maybe that's why? its linked to the /etc/localtime and /etc/timezone so should work, but doesn't unless you use moment.js.

**Comment by marc-gist** [comment]
Thanks again for your great node and responses! I found my issue.
Docker Node-Red v8, you must pass in "-e TZ=America/New_York"  or whatever your zone is.  using the -v /etc/localtime:/etc/localtime:ro isn't enough

**Comment by Hypnos3** [comment]
Thanks for your investigation.

 will still integrate the choice of the time zone in the configuration node. There is certainly the use case, where the environment of the Node-Red installation is not under control.

I let this issue open to not lose sight of that.

**Comment by Hypnos3** [comment]
The selection of the output format is implemented.

The selection for the output timezone is also already implemented. BUT hidden.

This affects so many places that I do not feel able to test it completely and see the danger to break more than to benefit.

So I have not decided to activate this. I will close the issue.
