### ISSUE TITLE
Set position on exact time

### ISSUE THREAD

**Issue by danyo2008** [rdmtc/node-red-contrib-sun-position#95]
Hello, 

**Describe the Problem**
I have set an Inject Node to a time intervall of 10 minutes, as mentioned in the documentation.
If i now deploy the flow, the rollershuter controll node initialize himself the first time after 10 minutes. A workaround is, to inject a message once the flow has been deployed/activated with a delay of a second or something like that.

But when the rollershutter should be closed at a exact time, e.g. sunset, an the sunset time is at 17:12:58, the node will not shutdown at the extract time, but up to 10 minutes later, as defined in the inject node, it will shut down. Is this the expected behaviour? Shall it work like this?

**Expected behavior**
If i set a shut down time in the evening at 18:30 o'clock, the shutter shall close at this time, not later....

Is there something, i make wrong?

**Screenshots**

**System information (please complete the following information):**

* Version (the latest version)
* Node-Red Version (the latest version)
* Hardware [Docker Container HASSIO)

**Comment by Hypnos3** [comment]
Hallo,

from Version 1.0.0 the node has a "auto trigger" option, which is off by default. When this is activated no external trigger node is required.

Then the node will triggered some seconds after Flow starts and
 -  if a rule with a time constrain is defined at this timestamp reaches
 - if sun time calculation is on and the sun is in the window every x minutes (I don't remember the exact time, but it is less than or equal 10 minutes)
- if the sun will be in the window in the next time in a short period of time (maybe 20 minutes) 
- in all other cases every x minutes defined in the settings next to the "auto trigger" option
If for a time different retrigger timestamps can be valid the shortest one will be used. (this means with a short time period in the settings this will be the maximum time for reteigger) 

With this you don't need the external trigger and it should work as expected.

The documentation is currently not finished, that's why this new functionality is not documented.

And at least :
This is a very new Function. I use it productive and I know others who uses it and I have not heard any problems, but there can be Bugs.
